### ISSUE TITLE
Crashes for Jelly Bean devices

### ISSUE THREAD

**Issue by sungjin0213** [gfranks/GFMinimalNotifications#5]
This library was working fine for Lollipop and Marshmallow devices, but for Jelly Bean devices, it crashes with following error. I investigated and it seems like it's trying to find class="com.github.gfranks.minimal.notification.GFMinimalNotificationLayout" in layout_minimal_notificatiion.xml, but it cannot find it. Would you please investigate and fix this?

```
 W/System.err: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:626)
 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:470)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
 W/System.err:     at com.github.gfranks.minimal.notification.GFMinimalNotification.<init>(GFMinimalNotification.java:244)
 W/System.err:     at com.github.gfranks.minimal.notification.GFMinimalNotification.make(GFMinimalNotification.java:271)
 W/System.err:     at com.github.gfranks.minimal.notification.GFMinimalNotification.make(GFMinimalNotification.java:315)
 W/System.err:     at com.cooperworks.ziptextconsumer.utilities.ZipInAppBanner$1.run(ZipInAppBanner.java:44)
 W/System.err:     at android.os.Handler.handleCallback(Handler.java:730)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
 W/System.err:     at android.os.Looper.loop(Looper.java:137)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5414)
 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
 W/System.err:     at dalvik.system.NativeStart.main(Native Method)
 W/System.err: Caused by: java.lang.reflect.InvocationTargetException
 W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
 W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:600)
 W/System.err:  ... 16 more
 W/System.err: Caused by: android.view.InflateException: Binary XML file line #3: Error inflating class <unknown>
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:626)
 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
 W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:463)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
 W/System.err:     at com.github.gfranks.minimal.notification.GFMinimalNotificationLayout.<init>(GFMinimalNotificationLayout.java:69)
 W/System.err:  ... 19 more
 W/System.err: Caused by: java.lang.reflect.InvocationTargetException
 W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
 W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:600)
 W/System.err:  ... 25 more
 W/System.err: Caused by: java.lang.NumberFormatException: Invalid int: "res/color/abc_primary_text_material_dark.xml"
 W/System.err:     at java.lang.Integer.invalidInt(Integer.java:138)
 W/System.err:     at java.lang.Integer.parse(Integer.java:375)
 W/System.err:     at java.lang.Integer.parseInt(Integer.java:366)
 W/System.err:     at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:122)
 W/System.err:     at android.content.res.TypedArray.getInt(TypedArray.java:255)
 W/System.err:     at android.widget.ImageView.<init>(ImageView.java:163)
 W/System.err:     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:57)
 W/System.err:     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
 W/System.err:  ... 28 more
```

**Comment by gfranks** [comment]
After pushing the 2.0 release, this is no longer an issue. A complete re-design has taken place and I am no longer using the GFMinimalNotificationLayout. It was a flawed design and not up to the google design guidelines. If you want to continue to use versions below 2.0, you may fork and refactor any code to make this runnable within your application.

**Comment by gfranks** [comment]
Fixed. This should be address in version 2.1
